name = "nada"
version = "0.1.0"
authors = [""]

[[programs]]
path = "src/wordle.py"
name = "wordle"
prime_size = 128

[[programs]]
path = "src/secret_addition.py"
name = "secret_addition"
prime_size = 128